version: '3.8'
services :
  fast_api:
    env_file:
      - ./.env
    build:
      context: .
    command: 'python server.py'
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    depends_on:
      - click_house_server
    links:
      - click_house_server
  click_house_server:
   image: yandex/clickhouse-server
   ports:
   - "${CLICK_HOUSE_PORT}:${CLICK_HOUSE_PORT}"
   - "${CLICK_HOUSE_HTTP_PORT}:${CLICK_HOUSE_HTTP_PORT}"
   ulimits:
    nproc: 65535
    nofile:
     soft: 262144
     hard: 262144